version: '3'
services:  
   web:
    stdin_open: true
    build: 
        context: .
        dockerfile: Dockerfile.dev
    environment:    
        - CHOKIDAR_USEPOLLING=true
    ports: 
        - "8080:3000"
    volumes: 
        - /app/node_modules
        - .:/app